import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const matter = localFont({
  src: [
    { path: "../../public/fonts/matter/Matter-Regular.otf", weight: "400", style: "normal" },
    { path: "../../public/fonts/matter/Matter-Medium.otf", weight: "500", style: "normal" },
  ],
  variable: "--font-matter",
  display: "swap",
});

const chivoMono = localFont({
  src: [
    { path: "../../public/fonts/chivo-mono/ChivoMono-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../public/fonts/chivo-mono/ChivoMono-Medium.ttf", weight: "500", style: "normal" },
  ],
  variable: "--font-chivo-mono",
  display: "swap",
});
import { WalletProvider } from "@/components/wallet-context";
import { TopNavConditional } from "@/components/top-nav-conditional";
import { ThemeProvider } from "@/components/theme-context";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${matter.variable} ${chivoMono.variable}`}> 
      <body className="antialiased font-sans">
        <ThemeProvider>
          <WalletProvider>
            <TopNavConditional />
            {children}
          </WalletProvider>
          <Toaster position="bottom-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
