import type { Metadata } from "next";
import "./globals.css";
import { WalletProvider } from "@/components/wallet-context";
import { TopNav } from "@/components/top-nav";
import { ThemeProvider } from "@/components/theme-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <ThemeProvider>
          <WalletProvider>
            <TopNav />
            {children}
          </WalletProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
